# Generated by Django 4.1 on 2024-11-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='check_in',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
