# Generated by Django 4.1 on 2024-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_check_in_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
