# Generated by Django 4.1 on 2024-11-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_date_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nombre',
        ),
    ]
