# Generated by Django 4.1 on 2024-11-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_rename_name_client_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='department',
            new_name='alojamiento',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='client',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='fecha_inicio',
        ),
    ]
