# Generated by Django 4.1 on 2024-11-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_department_reservation_alojamiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='capacity',
            new_name='capacidad',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='availability',
            new_name='disponibilidad',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='nombre',
        ),
    ]
