# Generated by Django 4.1 on 2024-11-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_rename_capacity_department_capacidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='alojamiento',
            new_name='propiedad',
        ),
    ]
